### ISSUE TITLE
Simulation.py

### ISSUE THREAD

**Issue by marfar** [ianvermeulen/memristor_simulations#1]
@ianvermeulen Hello!
First of all I want to thank you for this code. Unfortunately I am getting an error, while running Simulation.py which is "The connect keyword argument is no longer available, call the connect method instead". Could you help me with this?

**Comment by amirna78** [comment]
Hi, Thanks for the code as well. I have the same issue when I am trying to run the code.
I am using Python 2.7.13. I  receive the following error : 

C:\Users\user>python C:\memristor_simulations-master\Simulation.py
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: c:\users\user\appdata\local\temp\brian_debug_vgdsd6.log  Additionally, you can also include a copy of the script that was run, available at: c:\users\user\appdata\local\temp\brian_script_fgvuw1.py Thanks! [brian2]
Traceback (most recent call last):
  File "C:\memristor_simulations-master\Simulation.py", line 10, in <module>
    Input,S,Output,D_syn,D = init_network()
  File "C:\memristor_simulations-master\NetworkLoader.py", line 68, in init_network
    connect = 'True')
  File "C:\Users\user\Anaconda2\lib\site-packages\brian2\synapses\synapses.py", line 634, in __init__
    raise TypeError('The connect keyword argument is no longer '
TypeError: The connect keyword argument is no longer supported, call the connect method instead.

 
Many thanks

**Comment by sammem** [comment]
TypeError: The connect keyword argument is no longer supported, call the connect method instead.

In the file, NetworkLoader.py, for the function Synapses() delete    connect = 'True'
and add synapse_name.connect() below the synapse function for connecting the neurons

  D_syn = Synapses(Output, D, pre = 'fire_post = True', 
                              post = 'inhibit_pre = True',
                              on_event = {'pre' : 'STDP_spike'})
  D_syn.connect()

and

  S = Synapses(Input, Output, model = model, 
                              pre = pre, 
                              post = post, 
                              on_event = {'post' : 'STDP_spike'})
  S.connect()

**Comment by luttapy** [comment]
This is an excellent design, many thanks! I am trying to create an SNN with Morris Lecar neurons, using your code as a base.

BTW, when I am running Simulation.py, I am getting the following error:

```
ERROR      Brian 2 ... Thanks! [brian2]
Traceback (most recent call last):
  File "Simulation.py", line 171, in <module>
    total_spikes = float(event_mon.sum_events)
  File "/usr/local/lib/python2.7/dist-packages/brian2/groups/group.py", line 398, in __getattr__
    raise AttributeError('No attribute with name ' + name)
AttributeError: No attribute with name sum_events
```

Could you please help?

**Comment by luttapy** [comment]
> This is an excellent design, many thanks! I am trying to create an SNN with Morris Lecar neurons, using your code as a base.
> 
> BTW, when I am running Simulation.py, I am getting the following error:
> 
> ```
> ERROR      Brian 2 ... Thanks! [brian2]
> Traceback (most recent call last):
>   File "Simulation.py", line 171, in <module>
>     total_spikes = float(event_mon.sum_events)
>   File "/usr/local/lib/python2.7/dist-packages/brian2/groups/group.py", line 398, in __getattr__
>     raise AttributeError('No attribute with name ' + name)
> AttributeError: No attribute with name sum_events
> ```
> 
> Could you please help?

Figured out the fix, all thanks to @mstimberg. Changed attribute from _sum_events_ to _num_events_.
